# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'AppWithFANAndFrameworkWithFAN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FBAudienceNetwork', '= 4.27.2'

  # Pods for AppWithFANAndFrameworkWithFAN

  target 'AppWithFANAndFrameworkWithFANTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppWithFANAndFrameworkWithFANUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
